name data_arrays_0_ext depth 256 width 32 ports mrw mask_gran 8 
name tag_array_ext depth 16 width 24 ports rw  
name tag_array_0_ext depth 16 width 23 ports mrw mask_gran 23 
name data_arrays_0_0_ext depth 256 width 32 ports mrw mask_gran 32 
